---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCuV1ICn2TBChSyTfIxQ557YLsTZgabvZQAdEn0CmSQseLlX6gf509bNMKdWb1xY6J2cEFilPt7rjpVKnjuG7zZUqnSBYbNafD0j15ih22W3b6NxLSMUWUqviYhk1f0lW2xNScFtLCj/MBxSDtCXBc6sWqQb2x9VDI/Gqs+Hgrwm8ayfXcgxvN0U39tVD413AuC/1E1Xhl/LKWDvxyjmvV8naNQFb48DJFOWmLfgFMYRky0vlt4kQiPgiY2sfUFExTKCBUkccGOxoQZrpOsz3IOVeNmY43Muig+xJxYD4XfBmJaKjAzlJdZgT+l04PwrLn6YUfVbRoU1/JQytE4ETojR58YBcbcDI3PKmbcq8u125hYCU119RfBoFzykmdYnTibAYjpdp8R5Hxuwv9d31VWBj86Rf9gTqJnFq1MXyZ3hB1hjbx3mKlC7erz3E4DvcqDdvOzzsWGdzCgNhFC7hrMZ2M1fRfW9OmyDPByudDVcI5/lV0xCPXhOJKEUbjyZHXU3ue4Mm0g1lBVlDs/fw7t0LiniiG8J/lnw5TU+Re5b59fJxJ1PomLr28bnLtWbU5xGpstIFxApZRa5Jtwn+as9FSzk5nF6p0kA6/DdCUB9tclB4QkjUfrI93YnZs8PDn/2jzdKZ+iSYiQpW79/HjokFGrt0iSXzjw5TofMTw+5ewONEBOI9dlMVzIZa4LUtQoK9v6d8QqX2z7KxreXAE=
    admin-user: AgARsFlngilh55cyzquQ9zrdZIJd974Ms3uuEggrXp1jRv0UPWm4JF3/G7gnRm+9atsUP2/oRXVVHU+4XwOnx5qTl49aQzXiQOYZA9+wF7r5s0zm5fMvFFN3laHGmX35qBd4bvGh/PMA5yyQ/vnOovHCLh+arVsfylgyq9nP0nRq/qeD+IMVaXBE4m4DHRZrBB/bWaHAdjgvyPnCCXXCZnYBf8mSf3TPp8tngQYl8I6tBwgRm5JO3uyvzXzES9h2xrCL6vbD26ocX465JwHayKrDw1a9lPg/pnyqWLxg113Coq8VoN4eUFCsyz+2TKBelyIv4LVPnigr5PwJz4liW4Yy06FK2WHCpRUl9fM/Aeu72sAM4Ebi42zDqKUvVYtNmKjF12Cf3XZ+MX5F94mWfZJ4B63Z81SI+J/FGUAVc0fgOkJgFCDzed77o522W0JWTbzTSOWDg5VtPDC+tBM2KO3t/3sBGmEvr/3G/jLOVgW94eNzEgRMial1+CVI5Sx+fg8cNG/qUyxymjz3ZTBRPYWvvAQ1y6E+xoAekEvYsTPGnqTvy4fKGKaGFaV8q7rLp76tww3UpdVAdrNoQkaJDS9dPadvtPF/pFe9M3ly75nVzh6rCVIxVqSOi4eGjp6F0E4ZjQGtMqMa7BljFz5rUz37URcv02NCxk1swgZ6c5EHWFVks0x8eATcJ4TpjigwxGjv4ola6A==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
